#!/bin/bash
usage() {
  echo "Usage: $0 ipaddress {on|off|status|cycle|fx fx_num}"
}

if [[ $1 =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$ ]]; then
  ip=$1
else
  echo "Missing IP address"
  usage
  exit 1
fi

http_code() {
  declare -A http_codes
  http_codes["000"]="Is the IP correct?"
  http_codes["200"]="OK"
  http_codes["301"]="Moved Permanently"
  http_codes["400"]="Bad Request"
  http_codes["404"]="Not Found"
  http_codes["500"]="Internal Server Error"
  http_codes["501"]="Not Implemented"
  code="${http_codes["$1"]}" 
  if [[ "$code" ]];
  then
    echo "$code ($1)"
  else
    echo "$1"
  fi
}

on() {
  return=$(curl -s -o /dev/null -w "%{http_code}\n" "http://$ip/win&T=1")
  http_code $return
}

off() {
  return=$(curl -s -o /dev/null -w "%{http_code}\n" "http://$ip/win&T=0")
  http_code $return
}

brightness() {
  http_codes=$http_codes
  brightness=$1
  if [[ ! "$brightness" ]];
  then
    brightness_help
    exit 1
  fi
  echo "Setting brightness to $brightness"
  return=$(curl -s -o /dev/null -w "%{http_code}\n" "http://$ip/win&A=$brightness")
  http_code $return
}

cycle() {
  effects="$2"
  if [[ ! "$1" ]];
  then
    cycle_help
    exit 1
  fi

  if [[ ! "$2" ]];
  then
    cycle_help
    exit 1
  fi

  while true
  do
    for i in $(echo $2 | sed "s/,/ /g")
    do
      echo -n "Setting WLED effect $i, status: "
      return=$(curl -s -o /dev/null -w "%{http_code}" "http://$ip/win&T=1&FX=$i")
      http_code $return
      sleep $1
    done
  done
}

fx() {
  if [[ ! "$1" ]];
  then
    fx_help
    exit 1
  fi
  curl -s -o /dev/null -w "%{http_code}\n" "http://$ip/win&T=1&FX=$1"
  http_code $return
}

status() {
  curl -sS "http://$ip/win" | xmllint --format -
  echo
}

fx_help() {
  echo "fx requires a 3rd argument specifying the effect, list of effects is available here:"
  echo "https://github.com/Aircoookie/WLED/wiki/List-of-effects-and-palettes"
}

brightness_help() {
  echo "brightness requires a 3rd argument specifying the brightness between 0 and 255"
}

cycle_help() {
  echo "cycle requires a 3rd and 4th argument specifying the duration and effects list"
  echo "wled-cmd ipaddress cycle duration \"comma separated effect list\""
  echo "wled-cmd 192.168.1.147 cycle 5 34,39,44,61,64,73,74,75,87,68,101,110"
}

case "$2" in
    on)
       on
       ;;
    off)
       off
       ;;
    brightness)
       brightness $3
       ;;
    cycle)
       cycle $3 $4
       ;;
    fx)
       fx $3
       ;;
    status)
       status
       ;;
    *)
       echo "Missing command"
       usage
       ;;
esac
